### ISSUE TITLE
PyPy or CPython?

### ISSUE THREAD

**Issue by murtyjones** [christophetd/docker-python-sandbox#13]
Hi - just curious if the normal docker image associated with this library relies on CPython or PyPy?

**Comment by christophetd** [comment]
The code in the container is run using the default Python interpreter (`python` or `python3`), so I'm guessing it relies on CPython.

**Comment by murtyjones** [comment]
Thanks! This repo seems like it'd be a great candidate to use with PyPy's sandboxing feature. I will look into it.
